### ISSUE TITLE
V5: link error in https://github.com/PacificBiosciences/SMRT-Link/wiki/Installing-SSL-Cert-issued-by-a-CA

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/SMRT-Link#101]
copy paste fails due to a space before 'gui'
bottom of the page
replace: Miscellaneous 2. link
by: $SMRT_ROOT/current/bundles/smrtlink-analysisservices-gui/current/private/pacbio/smrtlink-analysisservices-gui/wso2am-2.0.0/repository/logs/wso2carbon.log

**Comment by jkaralius** [comment]
Thank you @splaisan
