### ISSUE TITLE
fasta starting point for pipelines e.g. HGAP4 (pbsmrtpipe.pipelines.polished_falcon_fat) or resequencing (pbsmrtpipe.pipelines.sa3_ds_resequencing)

### ISSUE THREAD

**Issue by alimayy** [PacificBiosciences/SMRT-Link#121]
Hi,

I've been trying to find a way for a while now how I can use Sequel subread data in fasta format as input (starting point) for pbsmrtpipe pipelines such as HGAP4 and Resequencing. If you're wondering why, following sequencing, I'm interested in immediately archiving the bam file on disk and keeping only the fasta for downstream analyses, the most common in my case are HGAP4 assembly and arrow-polishing (of other assemblies).

For `pbsmrtpipe.pipelines.polished_falcon_fat`, I've tried (on-the-fly) converting the subreads.fasta to sam (bbmap) and then bam (samtools), and then indexing (pbindex) but I get errors while creating the .pbi. Therefore `dataset create --type SubreadSet ` fails and I cannot use pbsmrtpipe.

Is there any way to run`pbsmrtpipe.pipelines.polished_falcon_fat` (or `pbsmrtpipe.pipelines.sa3_ds_resequencing `) starting with fasta data such that the result will be the same with what you would get by running it via SMRT Link (assuming of course that the contents of the preset.json files used are the same)

Thanks in advance

**Comment by pb-cdunn** [comment]
This answer might not be entirely satisfying. It might not even work. It's definitely unsupported, so it could stop working at any release. But I sometimes use it internally.
```sh
pbsmrtpipe pipeline-id pbsmrtpipe.pipelines.pipe_falcon_with_fofn --debug -e e_01:in/fc_run.cfg -e e_02:in/files.fofn --preset-json=./preset.json
```
You would need to supply the fasta in a "FileOfFileNames", one file per line. And you would need to supply all Falcon settings in `fc_run.cfg`, as if you ran Falcon directly. And you still need the pbsmrtpipe "preset" file.

More info:
* https://github.com/PacificBiosciences/SMRT-Link/wiki/pbsmrtpipe
* https://github.com/pacificbiosciences/FALCON/wiki

However, that is not a full pipeline. Without input BAM, you will not be able to "polish", as Arrow requires information from Sequel.

Again, this is completely unsupported. Good luck.

**Comment by alimayy** [comment]
Thanks a lot for your answer. It _is_ actually pretty satisfying in the sense that I know for sure now what I should not focus on. :-) Thanks especially for the `falcon_with_fofn ` pointer.
