### ISSUE TITLE
smrtlink5.0.1 pbsv generates problematic VCF

### ISSUE THREAD

**Issue by ilyasoifer** [PacificBiosciences/SMRT-Link#127]
Hi, 
`vcf` file that pbsv smrtlink5.0.1 generates declares 

`##FORMAT=<ID=GT,Number=1,Type=Integer,Description="Genotype">`
However, Genotype format should be Type=String. Because of that it is impossible to read with pysam

Thanks!

**Comment by pb-dstucki** [comment]
This is fixed in SMRT Link v5.1.
https://www.pacb.com/support/software-downloads/
