### ISSUE TITLE
Subread dataset from instrument is not displayed in SMRT Link after import

### ISSUE THREAD

**Issue by jkaralius** [PacificBiosciences/SMRT-Link#15]
## Symptom

Subread datasets (the `subreadset.xml` file) are not visible in SMRT Link UI following import.
## Diagnosis

``` bash
# Re-run the import
$SMRT_ROOT/current/bundles/smrttools/smrtcmds/bin/pbservice import-dataset --host <smrtlink_host> --port 9091 --debug  /path/to/subreadset.xml 
```

A message indicating successful import, or reporting dataset already found should be reported.
Next, check that the web services return the dataset by type.  (This is how the SMRT Link UI gets it’s list):

``` bash
curl http://<smrtlink-host>:9091/secondary-analysis/datasets/subreads
```

If it doesn’t show up, then try the query by UUID (found in the SubreadSet XML `“UniqueId”` attribute)

``` bash
curl http://<smrtlink-host:9091>/secondary-analysis/datasets/<UniqueId>
```

If the dataset can be found by UUID, but not by type "subreads", then confirm the existence of a line defining run name in the `subreadset.xml` file:

``` bash
grep 'pbmeta:Name' /path/to/subreadset.xml
```

If this line does not exist, then follow the steps below to edit the dataset XML.
## Solution

If the dataset XML is not importing correctly and the 

``` xml
<pbmeta:Name></pbmeta:Name>
```

 tag is missing from the file, then backup and edit the file, then follow these steps to edit and reimport the dataset XML.

``` bash
# backup the subreadset.xml
cp /path/to/subreadset.xml /path/to/subreadset.xml.bak
```

Make the following edits to `/path/to/subreadset.xml`:

1)  Change the dataset XML UUID. For example,

``` xml
<pbds:SubreadSet UniqueId="783cdf57-9c63-4d40-9a69-2d61b2ad16ad" 
```

can be changed to 

``` xml
<pbds:SubreadSet UniqueId="a83cdf57-9c63-4d40-9a69-2d61b2ad16ad" 
```

(just change it to a unique value)
**Note that the UUID should start with a LETTER to avoid downstream issues with some secondary analysis tools**

2)  Add a 

``` xml
<pbmeta:Name></pbmeta:Name>
```

tag within

``` xml
<pbmeta:RunDetails></pbmeta:RunDetails>
```

For example,

``` xml
<pbmeta:RunDetails>
        <pbmeta:Name>RUN_NAME</pbmeta:Name>
        <pbmeta:TimeStampedName>r54099_20160304_202916</pbmeta:TimeStampedName>
        <pbmeta:CreatedBy>String</pbmeta:CreatedBy>
        <pbmeta:WhenCreated>0001-01-01T00:00:00</pbmeta:WhenCreated>
        <pbmeta:WhenStarted>2016-03-04T20:35:18.118914Z</pbmeta:WhenStarted>
</pbmeta:RunDetails>

```

The dataset XML can then be imported.

``` bash
# Import Dataset
$SMRT_ROOT/current/bundles/smrttools/smrtcmds/bin/pbservice import-dataset --host <smrtlink_host> --port 9091 --debug /path/to/subreadset.xml
```

**Comment by jkaralius** [comment]
bug 31820

**Comment by jffkm** [comment]
solution worked well. thanks for tracking. i'll re-test with the 3.0.5 instrument software upgrade to see if auto import works and will let you know

**Comment by jffkm** [comment]
updating system software worked to import from the CLI while updating web services.

**Comment by jkaralius** [comment]
Solution updated.  Dataset XMLs were found to be missing run name definition.  New solution is to add run name to `subreadset.xml`, change the UUIID, and reimport.

**Comment by RobinQi** [comment]
Hi jkaralius,
Is it ok to auto import dataset for SMRT Link v3.1 and ICS 3.1? Can you give me some suggestions if it is ok?
Thanks.
