### ISSUE TITLE
LDAP passwords are sent to server without encryption

### ISSUE THREAD

**Issue by ibebio** [PacificBiosciences/SMRT-Link#37]
It seems that it is not possible to set up TLS encryption when configuring LDAP authentication for SMRTLink 3.1.0 and 3.1.1. The passwords are sent in clear text and are seen in the TCP dump, together with the user name. Our institute requires password encryption, which makes LDAP authentication as it is now not usable for us. By itself, sending unencrypted passwords over the network is a quite severe security isssue.

Are there any plans to add TLS encryption in SMRTLink? 

Thanks, Ilja

**Comment by jkaralius** [comment]
Hi Ilja,

Thank you for bringing this to our attention.  I have filed a bug to investigate this and hope to have a solution in an upcoming release.  We will followup with you when there is new information to share.

**Comment by jkaralius** [comment]
SMRT Link now uses WSO2 for securly managing User Authentication through LDAP.
See: https://github.com/PacificBiosciences/SMRT-Link/wiki/SMRT-Link-User-Authentication-and-Roles
