### ISSUE TITLE
Insert length greater than polymerase length.

### ISSUE THREAD

**Issue by WenchaoLin** [PacificBiosciences/SMRT-Link#42]
I can't understand why insert length greater than polymerase length. 

![xxx](https://cloud.githubusercontent.com/assets/5101698/18735055/4caa7e88-80ad-11e6-806b-31ad80833662.png)

**Comment by jkaralius** [comment]
Hi @WenchaoLin,

This is a known issue for 3.1.1.  We plan to have this fixed in the next release.

Joey
