### ISSUE TITLE
Arrow does not run with the message "Arrow: unsupported chemistries found"

### ISSUE THREAD

**Issue by IEkAdN** [PacificBiosciences/SMRT-Link#67]
Hello,

I tried to run arrow (SMRT-Link 3.1.1) against an output of pbalign, but arrow failed with the message `Arrow: unsupported chemistries found: (unknown)`
The sequencing was done with Seuquel System, a DNA binding kit v1.0, and a sequencing kit v1.2.1, so I set `v1.0-v1.2.1`, `V1.0-V1.2.1`, `v1.0`, `V1.0`, `v1`, `V1`, `v1.2.1`, or `V1.2.1` to the option `-p` and reran arrow, but in all cases it failed with the same error message (the string in the bracket was turned into the designated one).
Is there any possible cause for this error?

**Comment by danshu** [comment]
Hi,

I have the same problem with you. My sequel data is of S/P2-C2 chemistry. You may check you data using pbvalidate which will show you DNA binding kit version and sequencing kit version like this:
    <BindingKit>100-619-300</BindingKit>
    <SequencingKit>100-620-000</SequencingKit>
Then you may check the mapping file under pbcore directory, just like this one (https://github.com/PacificBiosciences/pbcore/blob/master/pbcore/chemistry/resources/mapping.xml). I believe this is the mapping file that map kits verisons to chemistry versions and if you can not find corresponding kit verisons then it means that you sequening chemistry is not supported yet.

I also want to ask if S/P2-C2 chemistry is different from S/P1-C1 chemistry in terms of polishing using arrow. If there is no major difference, then actually I can manage to polish with arrow recognizing my data as of S/P1-C1 chemistry.

Best,
Danshu

**Comment by IEkAdN** [comment]
Thank you for your response, Danshu.

My data contained the information `BINDINGKIT=100-619-300;SEQUENCINGKIT=100-902-100;BASECALLERVERSION=3.1.1.182013`, therefore by setting `S/P1-C1.2` to `-p`, I could run arrow successfully.
I really appreciate your help.

Best,
IEkAdN

**Comment by ebioman** [comment]
@danshu , thank you very much. This worked similarly for me with the parameter  ``S/P2-C2/5.0`` according to pbvalidate and the pbcore table. Does anybody know the source of it actually? These were non-treated files directly received by smrtpipe

**Comment by WenchaoLin** [comment]
You need to install SMRTLINK Chemistry Bundle v5.0.1 patch. Go to https://www.ngsgo.com/archives/2767.html for details.
