### ISSUE TITLE
Disable authentication.

### ISSUE THREAD

**Issue by vatese** [PacificBiosciences/SMRT-Link#81]
Hello,

I have no access to any documentation for SMRT Link 4.0.0.

I was wondering if there is a way to disable all authentication. 

I noticed this on the config.json:

"ENABLE_AUTH": false,

But authentication is still required.

Thanks!

**Comment by jkaralius** [comment]
Hi @vatese 

SMRT Link documentation can be found at http://www.pacb.com/support/software-downloads/

The LDAP-related settings in `$SMRT_ROOT/userdata/data/config.json` are obsoleted by WSO2, which manages user rights and roles starting with SMRT Link v4.0.0.  At this time authentication cannot be turned off, the default user profile is `admin`, pw: `admin`.
