### ISSUE TITLE
VCF version 3.3 produced ?

### ISSUE THREAD

**Issue by colindaven** [PacificBiosciences/SMRT-Link#85]
Hi,

I recently received bacterial SNVs from our PacBio provider which were output by SMRT Link. Basically, I want to view these in JBrowse, which can only read later - VCF4.0 and 4.1 formats.

Strangely, these are in VCF3.3 format, which is practically useless today. I had literally no idea this format existed until very recently despite working on SNV for years.

So I tried the VCFtools converter : no luck. Any ideas ? GFF conversion would work, but it seems strange to output such old formats, was a run option not set properly ?

```
 zcat job-57-4914a6f3-b37f-4562-9d38-8d5f85514fc5-output.vcf.gz | vcf-convert -r /lager2/rcug/seqres/PA/NC_008463.fa > job-57_out2_vcf4.vcf
Eh?: NC_008463.1:732714 .. GC AT

 at /mnt/ngsnfs/tools/miniconda2/lib/perl5/site_perl/5.22.0/Vcf.pm line 172, <STDIN> line 29.
        Vcf::throw(Vcf3_3=HASH(0x801758), "Eh?: NC_008463.1:732714 .. GC AT\x{a}") called at /mnt/ngsnfs/tools/miniconda2/lib/perl5/site_perl/5.22.0/Vcf.pm line 1619
        VcfReader::event_type(Vcf3_3=HASH(0x801758), HASH(0xe09a10), "AT") called at /mnt/ngsnfs/tools/miniconda2/bin/vcf-convert line 113
        main::convert_file(HASH(0x7caf30)) called at /mnt/ngsnfs/tools/miniconda2/bin/vcf-convert line 12
```

Thanks,
Colin

**Comment by colindaven** [comment]
I see now GFF and bed were also created. The GFF would appear as a valid workaround.

**Comment by colindaven** [comment]
It's a shame the developers aren't really interested in getting Pacbio to deliver relevant output formats for variant calling. I have recommended other platforms in the meantime which we will use in the future. At least bbmaps callvariants could generate VCF4.x SNV results from pacbio bams.

**Comment by nlhepler** [comment]
@colindaven, I'm happy to report that couldn't be further from the truth! You'll find that the VCFs produced by SMRTLink 5.0.1 (released last month) are in VCF 4.x format, which we will be supporting going forward.
