### ISSUE TITLE
Targeted_isoseq blasr failure

### ISSUE THREAD

**Issue by lotard** [PacificBiosciences/SMRT-Link#89]
I'm trying to reduce the number of cluster I get from Iso-seq analysis. I'm toying with some independent post-isoseq clustering / multiple alignment / consensus calling approaches (uclust, cdhit, muscle), but --targeted_isoseq flag seemed like something to try as well. NB: "What to do after isoseq clustering" suggestions won't work well (I think), because I'm sequencing structural variants, not RNA.

Unfortunately, --targeted_isoseq fails at blasr realignment level:

The command:
```
pbtranscript cluster clusterOut/isoseq_flnc.fasta \
                     clusterOut/consensus.fasta \
  --targeted_isoseq --quiver --nfl_fa isoseq_nfl.fasta \
  -d clusterOut/ \
  --bas_fofn output.subread.xml
```

Error message:
```
RuntimeError: CMD exited with a non-zero code: blasr /lustre/scratch117/cellgen/team82/mk17/pacbio/workspace/ccs/clusterOut/1to2kb_part1/output/tmp.consensus.fasta /lustre/scratch117/cellgen/team82/mk17/pacbio/workspace/ccs/clusterOut/1to2kb_part1/output/tmp.consensus.fasta --sa /lustre/scratch117/cellgen/team82/mk17/pacbio/workspace/ccs/clusterOut/1to2kb_part1/output/tmp.consensus.fasta.sa --bestn 20 --nCandidates 100 --minPctIdentity 95 --maxLCPLength 15 -m 5 --maxScore -2000 --nproc 24 --out /lustre/scratch117/cellgen/team82/mk17/pacbio/workspace/ccs/clusterOut/1to2kb_part1/output/tmp.consensus.fasta.self.blasr 1>/dev/null 2>/dev/null,
```

Here’s what I get when I run the last command separately (NB: the .fasta.sa file doesn’t exist)
```
clusterOut/output/tmp.consensus.fasta.sa is not a valid suffix array. 
 Make sure it is generated with the latest version of sawriter
```

Maybe there's an issue preventing the creation of the suffix array. Any ideas?

I would also welcome alternative suggestions as to reducing the number of clusters (at the cost of precision, if need be), perhaps changing the undocumented --ece_penalty and --ece_min_len parameters.

**Comment by uqvirg** [comment]
Hi,
Maybe you just have a " Disk quota exceeded"
Cheers,
Virginie

**Comment by lotard** [comment]
Got it sorted with help of @Magdoll here:
https://github.com/PacificBiosciences/IsoSeq_SA3nUP/issues/16
